### ISSUE TITLE
Create training manager report

### ISSUE THREAD

**Issue by SaeidBarzegar** [ehsmohammadi/HPMS#47]
[ResultSheetForTrainingManager.pdf](https://github.com/ehsmohammadi/HPMS/files/499989/ResultSheetForTrainingManager.pdf)

**Comment by ehsmohammadi** [comment]
I studied the file that is inserted here, 
because of big data that is transferred from server to client, this interface that is described here could not be implemented and some changes is required in design of this page . 
I think showing training fields and their data in continuously  is point of change and we should change interface design from there. 
By the way, i must talk with Mr.Jabari and Ms.Mousavi  about the view problem. 
Before that  i must design a solution for choosing responsible person for  training  every unit.

**Comment by ehsmohammadi** [comment]
After talking with Ms.Mousavi , I realize that there is no one who is responsible for training  each of unit , as I understand, there is one person for training all of unit and company in holding, and  an implementation and designing for this solution is waste of time .
About view section, we came up with this solution : 
First, showing the certain periods with suitable status for showing result in drop down list.
Second, by selecting one of that periods , showing certain indices with correct condition as training fields. 
Third, by selecting one of that indices, showing related employee in paging style.

**Comment by ehsmohammadi** [comment]
Tasks for doing this new issue : 
1. Create view , view model, change presentation controller and change service wrapper  
2. Create web api controller method , facade service method for fetching item from database  and send to presentation

**Comment by ehsmohammadi** [comment]
Create View View model ... was finished , and we fetch all training fields from server 
After that we must provide a link for going to new page

**Comment by ehsmohammadi** [comment]
Start create link in home page which the education responsible person can reach to his/her page

**Comment by ehsmohammadi** [comment]
All thing with one person employee number was created and all thin in order now 
and we must publish project on server

**Comment by ehsmohammadi** [comment]
all thing in order now and we publish the application in production environment
